### ISSUE TITLE
LineTooLong conflicts with ArrayDeclaration.MultiLineNotAllowed

### ISSUE THREAD

**Issue by simPod** [cdn77/coding-standard#24]
This violates `Cdn77CodingStandard.Files.LineLength.LineTooLong`:

```php
[
     'errors' => ["Command cannot be used over the API at this time. To see ASCII output, set format='te"],
],
```

I cannot do

```php
[
     'errors' => [
        "Command cannot be used over the API at this time. To see ASCII output, set format='te"
    ],
],
```
That violates `Squiz.Arrays.ArrayDeclaration.MultiLineNotAllowed`. What's the recommended solution?

**Comment by grongor** [comment]
You should be able to split the string onto multiple lines. This is a general rule when the cause `LineTooLong` is one long string.
